"""
Django settings for syyd project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r=9)v+&)2!!0lr$6*ozfd-^q+(88@god3%mxj##v_9nxpvtxav'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'book',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'syyd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'syyd.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'syyd',
        'USER': 'syyd_user',
        'PASSWORD': '19880404h.',
        'HOST': 'localhost',
        'PORT': 3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] [%(filename)s:%(lineno)d] %(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
            'level': 'DEBUG',
        },
        'crawl_info_handler': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': '%s/logs/crawl_info.log' % BASE_DIR,
            'when': 'D',  # 每天一切割日志
            'interval': 1,
            'backupCount': 10,
            'formatter': 'standard',
            'level': 'INFO',
        },
        'crawl_warning_handler': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': '%s/logs/crawl_warn.log' % BASE_DIR,
            'when': 'D',  # 每天一切割日志
            'interval': 1,
            'backupCount': 10,
            'formatter': 'standard',
            'level': 'WARNING',
        },
        'crawl_error_handler': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': '%s/logs/crawl_error.log' % BASE_DIR,
            'when': 'D',  # 每天切割日志
            'interval': 1,
            'backupCount': 10,
            'formatter': 'standard',
            'level': 'ERROR',
        }
    },
    'loggers': {
        'crawl_info': {
            'handlers': ['crawl_info_handler', 'console'] if DEBUG else ['crawl_info_handler'],
            'level': 'INFO',
            'propagate': False,
        },
        'crawl_warning': {
            'handlers': ['crawl_warning_handler', 'console'] if DEBUG else ['crawl_warning_handler'],
            'level': 'WARNING',
            'propagate': False,
        },
        'crawl_error': {
            'handlers': ['crawl_error_handler', 'console'] if DEBUG else ['crawl_error_handler'],
            'level': 'ERROR',
            'propagate': False,
        }
    }
}

